# title: Minimal theme
# logo: /assets/img/1684833548001.jfif
# description: Minimal is a theme for GitHub Pages.
# show_downloads: true
# google_analytics:
# theme: jekyll-theme-minimal

title: <p align="center"> Mridul Gupta </p>
logo: /assets/img/1684833548001.jfif

description:
  <p align="center">
  <a href="https://www.linkedin.com/in/mridul-gupta-2906/">LinkedIn</a> |
  <a href="https://github.com/mridulgupta2906">GitHub</a> | 
  <a href="https://www.kaggle.com/playmakerg">Kaggle</a> | 
  <a href="mridulgupta2906@gmail.com">Gmail</a> | 
  <a href="/pdf/Mridul Gupta.pdf">Resume</a>
  
  <br>   
  Individual with enthusiasm in field of
  Computer Science, Space and Technology .
  Always ready for trying new things and
  solving problems related to real world.
  Currently looking for full-time opportunities in field of Data Science.
  <br>
  </p>



theme: jekyll-theme-minimal
